# Generated by Django 3.1.4 on 2021-02-07 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0003_auto_20210104_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(default=datetime.datetime.today)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomy.taxonomy')),
            ],
        ),
    ]
