# Generated by Django 3.1.4 on 2021-01-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20210104_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.taxonomy'),
        ),
    ]
